language: python
python:
  - 2.7
  - pypy
before_script:
  - mysql -e 'create database test_toradbapi;'
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install MySQL-python; fi
  - pip install -r requirements.txt
script: python setup.py test
